#
# Server ID and UID can be configured automatically using /mcmetrics setup.
# KEEP THESE VALUES SECRET!
# More information: https://docs.mcmetrics.net/quickstart
#
server_id: ""
uid: ""

# Should the plugin send anonymous usage data to BStats? This helps us track plugin usage across servers.
# This option needs a restart to take effect.
enable-bstats: true

# Automatically subtracts a percentage from payment amounts to account for Tebex & transaction fees.
# For example, setting this to 0.05 will subtract 5% from all payments.
# Set to 0.0 to disable.
payment-fee: 0.00

# Sends additional debug information to the console.
debug: false